[package]
name = "hematite"
version = "0.1.0"
edition = "2021"
autors = ["Yeji Han <yejicse@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.11.4"
